easy_admin:
    site_name: 'TOP - Manager Panel'
    entities:
        News:
            class: App\Entity\News
            file_base_path: '..\uploads\files\'
            list:
                fields:
                    - { property: 'photo', type: 'image' ,  base_path: '%app.path.files%' }
            show:
                fields:
                    - { property: 'image', type: 'image', base_path: '%files%' }

            form:
                fields:
                    - { property: 'Title' }
                    - { property: 'Date'}
                    - { property: 'Content', type: 'text_editor' }
                    - { property: 'imageFile', type: 'vich_image' }
        Notice:
            class: App\Entity\Notice
            file_base_path: '..\uploads\files\'
            list:
                fields:
                    - { property: 'photo', type: 'image' ,  base_path: '..\uploads\files\' }
            form:
                fields:
                    - { property: 'Title' }
                    - { property: 'Date'}
                    - { property: 'Content', type: 'text_editor' }
                    - { property: 'photo', type: 'file_upload' , type_options: { upload_filename: '[year]/[month]/[day].[extension]' , upload_dir: 'public\uploads\files\' } }
        User:
            class: App\Entity\User
        Subject:
            class: App\Entity\Subject
