easy_admin:
    site_name: 'TOP - Manager Panel'
    entities:
        News:
            class: App\Entity\News
        Notice:
            class: App\Entity\Notice
        User:
            class: App\Entity\User
        Subject:
            class: App\Entity\Subject
